dist: xenial
language: minimal
services:
  - docker
env:
  global:
    - TRAVIS_DEBIAN_DERIVATIVE="ubuntu"
    - TRAVIS_DEBIAN_COMPONENTS="main restricted universe multiverse"
    - TRAVIS_DEBIAN_MIRROR="http://us-east-1.ec2.archive.ubuntu.com/ubuntu"
    - TRAVIS_DEBIAN_TARGET_DIR="${TRAVIS_BUILD_DIR}/dist"
    - DEB_BUILD_OPTIONS="parallel=4"
  matrix:
    - TRAVIS_DEBIAN_DISTRIBUTION="xenial" TRAVIS_DEBIAN_BACKPORTS="xenial-backports"
    - TRAVIS_DEBIAN_DISTRIBUTION="bionic" TRAVIS_DEBIAN_BACKPORTS="bionic-backports"
script:
  - wget -O- http://travis.debian.net/script.sh | sh -
